const WHITECOLOR = "rgb(255, 255, 255)";
const BLACKCOLOR = "rgb(0, 0, 0)";
const GRAYCOLOR = "rgb(128, 128, 128)";
const GREENCOLOR = "rgb(0, 155, 0)";
const BRIGHTBLUECOLOR = "rgb(0, 50, 255)";
const BROWNCOLOR = "rgb(174, 94, 0)";

const BOARDWIDTH = 8;
const BOARDHEIGHT = 8;

const TEXTBGCOLOR1 = BRIGHTBLUECOLOR
const TEXTBGCOLOR2 = GREENCOLOR
const GRIDLINECOLOR = BLACKCOLOR
const TEXTCOLOR = BLACKCOLOR
const TEXTWHITECOLOR = WHITECOLOR
const TEXTGRAYCOLOR = GRAYCOLOR
const HINTCOLOR = BROWNCOLOR

const EMPTY = 0;
const BLACK = 1;
const WHITE = 2;
const HINT = 3;